export const brands = {
  resultado: true,
  mensaje: "Datos 190",
  datos: [
    { id: "3M", nombre: "3M" },
    { id: "AB", nombre: "ASUS" },
    { id: "AC", nombre: "ACCO" },
    { id: "AD", nombre: "ADATA" },
    { id: "AE", nombre: "ACER" },
    { id: "AH", nombre: "AMD " },
    { id: "AI", nombre: "ARTLINE " },
    { id: "AK", nombre: "ACTECK" },
    { id: "AL", nombre: "ALFRA" },
    { id: "AN", nombre: "AINK " },
    { id: "AQ", nombre: "ACUACOLOR " },
    { id: "AU", nombre: "ACUARELO " },
    { id: "AZ", nombre: "AZOR " },
    { id: "BA", nombre: "BACO" },
    { id: "BB", nombre: "BIOSTAR " },
    { id: "BD", nombre: "BITEDEFENDER" },
    { id: "BE", nombre: "BEROL " },
    { id: "BI", nombre: "BIC" },
    { id: "BN", nombre: "BENQ" },
    { id: "BO", nombre: "BROTHER" },
    { id: "BR", nombre: "BARRILITO" },
    { id: "BU", nombre: "BULLY " },
    { id: "CA", nombre: "CANON" },
    { id: "CF", nombre: "CUENTA FACIL " },
    { id: "CI", nombre: "CHECK IT " },
    { id: "CL", nombre: "CELICA" },
    { id: "CT", nombre: "CORTY " },
    { id: "DE", nombre: "DELL" },
    { id: "DH", nombre: "DAHUA" },
    { id: "DT", nombre: "DATAPAC" },
    { id: "EA", nombre: "ESTRELLA" },
    { id: "EB", nombre: "ESET" },
    { id: "ED", nombre: "ELMERS" },
    { id: "EE", nombre: "ESSELTE" },
    { id: "EO", nombre: "EUROCOLORS " },
    { id: "EP", nombre: "EPSON" },
    { id: "ER", nombre: "EUROFORMAS " },
    { id: "EU", nombre: "EUROMAC " },
    { id: "FE", nombre: "FELLOWES" },
    { id: "FO", nombre: "FORMASTOCK" },
    { id: "FV", nombre: "FACIA VISION" },
    { id: "GE", nombre: "GEO" },
    { id: "GN", nombre: "GENERAL ELECTRIC" },
    { id: "HE", nombre: "HERCULES" },
    { id: "HN", nombre: "HP ENTERPRISE" },
    { id: "HP", nombre: "HEWLETT PACKARD" },
    { id: "HS", nombre: "HISENSE" },
    { id: "HU", nombre: "HUAWEI" },
    { id: "IE", nombre: "INTEL " },
    { id: "IT", nombre: "INTELLINET " },
    { id: "JP", nombre: "JANEL" },
    { id: "KA", nombre: "KASPERSKY" },
    { id: "KB", nombre: "KOBLENZ" },
    { id: "KE", nombre: "KENSINGTON" },
    { id: "KI", nombre: "KINERA " },
    { id: "KN", nombre: "KINGSTON" },
    { id: "KO", nombre: "KODAK" },
    { id: "KR", nombre: "KORES" },
    { id: "LC", nombre: "LINC" },
    { id: "LE", nombre: "LEXMARK" },
    { id: "LF", nombre: "LEFORT " },
    { id: "LG", nombre: "LG ELECTRONICS" },
    { id: "LN", nombre: "LENOVO" },
    { id: "LO", nombre: "LOGITECH" },
    { id: "LV", nombre: "LENOVO IDEA" },
    { id: "MA", nombre: "MAPASA " },
    { id: "MB", nombre: "MAE " },
    { id: "MC", nombre: "PERFECT CHOICE" },
    { id: "MG", nombre: "MAGISTRAL " },
    { id: "MI", nombre: "MICROSOFT" },
    { id: "MN", nombre: "MANHATTAN " },
    { id: "MP", nombre: "MAPED" },
    { id: "MR", nombre: "MOTOROLA" },
    { id: "MS", nombre: "MEGA SIZE " },
    { id: "NA", nombre: "NASSA " },
    { id: "NE", nombre: "NEXTEP" },
    { id: "NR", nombre: "NORTON" },
    { id: "NX", nombre: "NEXTEP SOLUCIONES" },
    { id: "OF", nombre: "OFFIZ " },
    { id: "OK", nombre: "OKIDATA" },
    { id: "OX", nombre: "OXFORD" },
    { id: "PB", nombre: "PRITT " },
    { id: "PE", nombre: "PELIKAN" },
    { id: "PF", nombre: "PROLICOM" },
    { id: "PG", nombre: "PEGASO " },
    { id: "PH", nombre: "PILOT PEN" },
    { id: "PI", nombre: "PILOT" },
    { id: "PJ", nombre: "PEERLEES" },
    { id: "PK", nombre: "PARKER " },
    { id: "PM", nombre: "PCM" },
    { id: "PP", nombre: "PAPERMATTE " },
    { id: "PQ", nombre: "PITS" },
    { id: "PV", nombre: "PRINT-RITE" },
    { id: "PY", nombre: "POLYCOM" },
    { id: "QA", nombre: "QFX" },
    { id: "RI", nombre: "RIHAN" },
    { id: "RL", nombre: "REALME" },
    { id: "RO", nombre: "ROLAPLICA " },
    { id: "RS", nombre: "RESISTOL " },
    { id: "SA", nombre: "SAMSUNG" },
    { id: "SB", nombre: "SOLA BASIC" },
    { id: "SC", nombre: "SCRIBE" },
    { id: "SD", nombre: "SANDISK " },
    { id: "SF", nombre: "STAFFORD " },
    { id: "SI", nombre: "SIGNAL " },
    { id: "SJ", nombre: "STARFILE" },
    { id: "SL", nombre: "SABLON " },
    { id: "SN", nombre: "SANFORD " },
    { id: "SO", nombre: "SONY" },
    { id: "SS", nombre: "SAMSILL" },
    { id: "SX", nombre: "SAXXON" },
    { id: "TQ", nombre: "TURQUOISE " },
    { id: "TR", nombre: "TRIPP-LITE" },
    { id: "TU", nombre: "TUK" },
    { id: "UN", nombre: "UNIBALL " },
    { id: "VE", nombre: "VERBATIM" },
    { id: "VO", nombre: "VORAGO" },
    { id: "VP", nombre: "VISION PLUS " },
    { id: "VV", nombre: "VIVOTEK" },
    { id: "WE", nombre: "WEAREVER " },
    { id: "WS", nombre: "WESTERN DIGITAL " },
    { id: "XE", nombre: "XEROX" },
    { id: "XI", nombre: "XIAOMI" },
    { id: "XZ", nombre: "XZEAL" },
    { id: "ZE", nombre: "ZEBRA" },
    { id: "CH", nombre: "COOLERMASTER " },
    { id: "CJ", nombre: "CREALITY" },
    { id: "CK", nombre: "CORSAIR" },
    { id: "EV", nombre: "EVGA" },
    { id: "GI", nombre: "GIGABYTE " },
    { id: "IA", nombre: "FURNIER" },
    { id: "LX", nombre: "LANIX" },
    { id: "MD", nombre: "MAD CATZ" },
    { id: "MF", nombre: "MSI" },
    { id: "PW", nombre: "PNY " },
    { id: "SK", nombre: "SEAGATE" },
    { id: "SQ", nombre: "STEREN" },
    { id: "TB", nombre: "TRIBE" },
    { id: "TE", nombre: "TECHZONE" },
    { id: "VA", nombre: "VIVO" },
    { id: "VX", nombre: "VOXART" },
    { id: "OS", nombre: "ONSUN" },
    { id: "KC", nombre: "KYOCERA" },
    { id: "VB", nombre: "VICA" },
    { id: "SW", nombre: "SMARTBIIT" },
    { id: "CQ", nombre: "CDP" },
    { id: "HR", nombre: "HONOR" },
    { id: "GU", nombre: "GUARDA" },
    { id: "NK", nombre: "NOKIA" },
    { id: "OO", nombre: "OPPO" },
    { id: "EF", nombre: "ECS" },
    { id: "GS", nombre: "G SKILL" },
    { id: "SZ", nombre: "SAPPHIRE " },
    { id: "TI", nombre: "TOSHIBA" },
    { id: "ZO", nombre: "ZOTAC " },
    { id: "TG", nombre: "TARGUS" },
    { id: "FR", nombre: "FORZA POWER TECHNOLOGIES" },
    { id: "TC", nombre: "TOSHIBA " },
    { id: "ZA", nombre: "ZEBRA" },
    { id: "AJ", nombre: "ASUS " },
    { id: "HO", nombre: "HONEYWELL" },
    { id: "PR", nombre: "PRINTAFORM" },
    { id: "OE", nombre: "ONE PLUS" },
    { id: "AF", nombre: "APC" },
    { id: "AW", nombre: "ARGOMTECH" },
    { id: "AX", nombre: "AMAZON" },
    { id: "CO", nombre: "COMPAQ" },
    { id: "DU", nombre: "DUPLIMAX" },
    { id: "JB", nombre: "JBL" },
    { id: "KD", nombre: "KYMA" },
    { id: "NC", nombre: "NACEB" },
    { id: "S0", nombre: "SIX GRAPHICS" },
    { id: "TN", nombre: "TECNO SPARK" },
    { id: "WI", nombre: "WIKO" },
    { id: "A0", nombre: "ARUBA" },
    { id: "AY", nombre: "ATL" },
    { id: "DX", nombre: "DIXON" },
    { id: "EY", nombre: "EASYSOFT" },
    { id: "H3", nombre: "H3C" },
    { id: "KX", nombre: "KLIP XTREME" },
    { id: "NS", nombre: "NEXXT SOLUTIONS" },
    { id: "NT", nombre: "NEXXT SOLUTIONS HOME" },
    { id: "P0", nombre: "POLICRAFT" },
    { id: "P1", nombre: "PRIMUS" },
    { id: "PZ", nombre: "POLITEC" },
    { id: "RD", nombre: "RODIN" },
    { id: "RR", nombre: "RODART" },
    { id: "TJ", nombre: "TCL" },
    { id: "XT", nombre: "XTECH" },
    { id: "EK", nombre: "ECLINE" },
  ],
};
