export const subcategories = {
  resultado: true,
  mensaje: "Datos 242",
  datos: [
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Laptop",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Desktop",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Notebook",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "All in One",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Pantallas Profesionales",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Accesorios",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Tablets",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Monitores",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Tarjetas - Adaptadores",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "10",
      nombre_subcategoria: "Workstation",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "UPS",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "14",
      nombre_subcategoria: "Al\u00e1mbricos",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Servidor de Valor",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "16",
      nombre_subcategoria: "Papel Copiadora",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Art\u00edculos de Escritura",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "18",
      nombre_subcategoria: "Cajones de dinero",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "19",
      nombre_subcategoria: "C\u00e1maras HD",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "20",
      nombre_subcategoria: "Accesorios",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "21",
      nombre_subcategoria: "Detectores de metal",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "23",
      nombre_subcategoria: "Esc\u00e1ner",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "99",
      nombre_subcategoria: "Bundles",
      id_categoria: "1",
      nombre_categoria: "Computo",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Impresoras L\u00e1ser",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Impresoras de Inyecci\u00f3n",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Impresoras Matriz de Punto",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Impresoras POS",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Plotters",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Multifuncionales",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Esc\u00e1neres",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Punto de Acceso",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "10",
      nombre_subcategoria: "Rotulador Electr\u00f3nico",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Accesorios",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "14",
      nombre_subcategoria: "Inal\u00e1mbricos",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Accesorios",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "16",
      nombre_subcategoria: "Papel Continuo",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Cuadernos Blocks y Libros",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "18",
      nombre_subcategoria: "Impresoras",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "19",
      nombre_subcategoria: "C\u00e1maras IP",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "20",
      nombre_subcategoria: "Servicios",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "21",
      nombre_subcategoria: "Contador de Billetes",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "23",
      nombre_subcategoria: "Software de Captura",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "99",
      nombre_subcategoria: "Bundle",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "101",
      nombre_subcategoria: "Bordadora",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "103",
      nombre_subcategoria: "Impresoras Fotograf\u00edas",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "105",
      nombre_subcategoria: "Impresoras 3D",
      id_categoria: "2",
      nombre_categoria: "Impresi\u00f3n y Multifuncionales",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Marcas",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Impresoras Matriz de Punto",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "USB",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Accesorios TV",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Plataformas de Juego Soportado",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Bundles",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Toners",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "10",
      nombre_subcategoria: "Tinta",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Barras y Supresores",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "14",
      nombre_subcategoria: "Telefon\u00eda M\u00f3vil",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Garant\u00edas",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "16",
      nombre_subcategoria: "Papel Cortado",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Did\u00e1cticos y de Dibujo",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "18",
      nombre_subcategoria: "Lectores",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "19",
      nombre_subcategoria: "DVR",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "23",
      nombre_subcategoria: "Servicios y Garant\u00edas",
      id_categoria: "3",
      nombre_categoria: "Consumibles",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "CD",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "DVD",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "USB",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Cintas de Almacenamiento",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Disco Duro",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Blu-Ray",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Flash Card - SD",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "10",
      nombre_subcategoria: "Cubierta para Disco",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Cables",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "14",
      nombre_subcategoria: "Accesorios",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Software Valor",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "16",
      nombre_subcategoria: "Papel Lustre",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Sujetadores y Portadocumentos",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "18",
      nombre_subcategoria: "Monitores y Pantallas",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "19",
      nombre_subcategoria: "Disco Duro",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "20",
      nombre_subcategoria: "Tel\u00e9fono IP",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "23",
      nombre_subcategoria: "Consumibles",
      id_categoria: "4",
      nombre_categoria: "Almacenamiento",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Pantallas Profesionales",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Televisores",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Accesorios TV",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Cintas de Almacenamiento",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Audio Hogar",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Televisores Hoteleros",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Digital Signage",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Consolas y Entretenimiento",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "10",
      nombre_subcategoria: "Bundles",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Accesorios",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "12",
      nombre_subcategoria: "Hogar",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "13",
      nombre_subcategoria: "Smart Home",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "14",
      nombre_subcategoria: "Bundles",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Unidad de Respaldo Valor",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Folders y Sobres",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "19",
      nombre_subcategoria: "Accesorios Videovigilancia",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "20",
      nombre_subcategoria: "Videoconferencia",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "23",
      nombre_subcategoria: "Accesorios",
      id_categoria: "5",
      nombre_categoria: "Electr\u00f3nica de Consumo",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "C\u00e1maras",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Videoc\u00e1maras ",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Videoproyectores ",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Disco Duro",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Pantallas para Proyecci\u00f3n",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Marcos Digitales",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Accesorios",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "C\u00e1maras de seguridad",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "10",
      nombre_subcategoria: "Miniproyectores",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Fuentes de Poder",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "14",
      nombre_subcategoria: "Accesorios Telefono Empresarial",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Servicio de Infraestructura",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "16",
      nombre_subcategoria: "Papel Rotafolio",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Organizadores y Cajas",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "18",
      nombre_subcategoria: "All in One",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "19",
      nombre_subcategoria: "Kit",
      id_categoria: "6",
      nombre_categoria: "C\u00e1mara Video y Proyecci\u00f3n",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Bocinas",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Aud\u00edfonos",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Micr\u00f3fono",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Manos Libres",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Digital Signage",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Accesorios",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Para Videojuegos",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Accesorios",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "10",
      nombre_subcategoria: "Seguridad",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Adaptador de Corriente",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Disco Duro Valor",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "16",
      nombre_subcategoria: "Papel Carb\u00f3n",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Sellos y Foliadores",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "18",
      nombre_subcategoria: "Esc\u00e1ner",
      id_categoria: "8",
      nombre_categoria: "Audio y Entretenimiento",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Tarjetas - Adaptadores",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Punto de Acceso",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Ruteador",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Multiplexores",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Switch",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Hub",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Accesorios",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Accesorios",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Equipo para Site",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "14",
      nombre_subcategoria: "Telefono IP",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Memorias Valor",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "16",
      nombre_subcategoria: "Papel Fax",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Carpetas",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "18",
      nombre_subcategoria: "Accesorios",
      id_categoria: "9",
      nombre_categoria: "Redes",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Aplicaciones",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Rotulador Electr\u00f3nico",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Tinta",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Cubierta para Disco",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Sistemas Operativos",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Miniproyectores",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Extensi\u00f3n de Garant\u00edas",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Seguridad",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Bundle",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Art\u00edculos de Oficina y Mobiliario",
      id_categoria: "10",
      nombre_categoria: "Software y Garant\u00edas",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "UPS",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Reguladores",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Barras y Supresores",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Cables",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Bater\u00eda y Cargadores",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Fuentes de Poder",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Inversores",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Adaptador de Corriente",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Equipo para Site",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "10",
      nombre_subcategoria: "Bundle",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "12",
      nombre_subcategoria: "Generador el\u00e9ctrico",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Cables Valor",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "16",
      nombre_subcategoria: "Papel amplio formato",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Hojas Notas y Formatos",
      id_categoria: "11",
      nombre_categoria: "Energ\u00eda y Cables",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Al\u00e1mbricos",
      id_categoria: "14",
      nombre_categoria: "Telefon\u00eda",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Inal\u00e1mbricos",
      id_categoria: "14",
      nombre_categoria: "Telefon\u00eda",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Telefon\u00eda M\u00f3vil",
      id_categoria: "14",
      nombre_categoria: "Telefon\u00eda",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Accesorios",
      id_categoria: "14",
      nombre_categoria: "Telefon\u00eda",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Bundles",
      id_categoria: "14",
      nombre_categoria: "Telefon\u00eda",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Accesorios Telefono Empresarial",
      id_categoria: "14",
      nombre_categoria: "Telefon\u00eda",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Telefono IP",
      id_categoria: "14",
      nombre_categoria: "Telefon\u00eda",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Bundle",
      id_categoria: "14",
      nombre_categoria: "Telefon\u00eda",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Art\u00edculos para Cortar",
      id_categoria: "14",
      nombre_categoria: "Telefon\u00eda",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Servidor de Valor",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Accesorios",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Garant\u00edas",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Software Valor",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Unidad de Respaldo Valor",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Servicio de Infraestructura",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Procesador Valor",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Disco Duro Valor",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Memorias Valor",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Cables Valor",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "12",
      nombre_subcategoria: "Fuente Poder Servidor Valor",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "13",
      nombre_subcategoria: "Switch Valor",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "14",
      nombre_subcategoria: "Bundle",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Enmicadoras y Cubiertas",
      id_categoria: "15",
      nombre_categoria: "Servidores y Almacenamiento",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Papel Copiadora",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Papel Continuo",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Papel Cortado",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Papel Lustre",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Papel Rotafolio",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Papel Am\u00e9rica",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Papel Carb\u00f3n",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Papel Fax",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Papel amplio formato",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Etiquetadoras",
      id_categoria: "16",
      nombre_categoria: "Papel",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Art\u00edculos de Escritura",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Cuadernos Blocks y Libros",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Did\u00e1cticos y de Dibujo",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Sujetadores y Portadocumentos",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Folders y Sobres",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Organizadores y Cajas",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Cintas y Pegamentos",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Sellos y Foliadores",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Carpetas",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "10",
      nombre_subcategoria: "Art\u00edculos de Oficina y Mobiliario",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "11",
      nombre_subcategoria: "Hojas Notas y Formatos",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "12",
      nombre_subcategoria: "Pizarrones y Accesorios",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "13",
      nombre_subcategoria: "Reglas y Equipo de Geometr\u00eda",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "14",
      nombre_subcategoria: "Art\u00edculos para Cortar",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "15",
      nombre_subcategoria: "Enmicadoras y Cubiertas",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "16",
      nombre_subcategoria: "Etiquetadoras",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Grapadoras",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "18",
      nombre_subcategoria: "Engargoladora",
      id_categoria: "17",
      nombre_categoria: "Oficina y Escolar",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Cajones de dinero",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Impresoras",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Lectores",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Monitores y Pantallas",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Software",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "All in One",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "Desktop",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "8",
      nombre_subcategoria: "Esc\u00e1ner",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "9",
      nombre_subcategoria: "Accesorios",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "17",
      nombre_subcategoria: "Engargoladora",
      id_categoria: "18",
      nombre_categoria: "Puntos de Venta",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "C\u00e1maras HD",
      id_categoria: "19",
      nombre_categoria: "Videovigilancia",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "C\u00e1maras IP",
      id_categoria: "19",
      nombre_categoria: "Videovigilancia",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "DVR",
      id_categoria: "19",
      nombre_categoria: "Videovigilancia",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Disco Duro",
      id_categoria: "19",
      nombre_categoria: "Videovigilancia",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Accesorios Videovigilancia",
      id_categoria: "19",
      nombre_categoria: "Videovigilancia",
    },
    {
      id_subcategoria: "6",
      nombre_subcategoria: "Kit",
      id_categoria: "19",
      nombre_categoria: "Videovigilancia",
    },
    {
      id_subcategoria: "7",
      nombre_subcategoria: "NVR",
      id_categoria: "19",
      nombre_categoria: "Videovigilancia",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Accesorios",
      id_categoria: "20",
      nombre_categoria: "Telefon\u00eda Empresarial",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Servicios",
      id_categoria: "20",
      nombre_categoria: "Telefon\u00eda Empresarial",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Tel\u00e9fono IP",
      id_categoria: "20",
      nombre_categoria: "Telefon\u00eda Empresarial",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Videoconferencia",
      id_categoria: "20",
      nombre_categoria: "Telefon\u00eda Empresarial",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Detectores de metal",
      id_categoria: "21",
      nombre_categoria: "Seguridad",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Contador de Billetes",
      id_categoria: "21",
      nombre_categoria: "Seguridad",
    },
    {
      id_subcategoria: "1",
      nombre_subcategoria: "Esc\u00e1ner",
      id_categoria: "23",
      nombre_categoria: "Digitalizaci\u00f3n de Documentos",
    },
    {
      id_subcategoria: "2",
      nombre_subcategoria: "Software de Captura",
      id_categoria: "23",
      nombre_categoria: "Digitalizaci\u00f3n de Documentos",
    },
    {
      id_subcategoria: "3",
      nombre_subcategoria: "Servicios y Garant\u00edas",
      id_categoria: "23",
      nombre_categoria: "Digitalizaci\u00f3n de Documentos",
    },
    {
      id_subcategoria: "4",
      nombre_subcategoria: "Consumibles",
      id_categoria: "23",
      nombre_categoria: "Digitalizaci\u00f3n de Documentos",
    },
    {
      id_subcategoria: "5",
      nombre_subcategoria: "Accesorios",
      id_categoria: "23",
      nombre_categoria: "Digitalizaci\u00f3n de Documentos",
    },
  ],
};
